name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=algolia
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin Brisk card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Spotandjake&repo=Brisk&theme=algolia
          path: profile/pin-brisk.svg
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Generate pin Grain card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=grain-lang&repo=grain&theme=algolia
          path: profile/pin-grain.svg
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name:  Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=algolia&langs_count=25
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate wakatime card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: username=Spotandjake&theme=algolia&v=4&langs_count=25
          path: profile/wakatime.svg
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "chore: Update README cards" || exit 0
          git push